"""empty message

Revision ID: 040d4f3e5858
Revises: 
Create Date: 2020-02-23 06:44:20.488715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040d4f3e5858'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column(
        'open_hours', sa.DateTime(), nullable=True))
    op.add_column('vendors', sa.Column(
        'close_hours', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'open_hours')
    op.drop_column('vendors', 'close_hours')
    # ### end Alembic commands ###### end Alembic commands ###
