"""empty message

Revision ID: 28caae1b112c
Revises: 
Create Date: 2020-02-23 00:13:15.687791

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_json


# revision identifiers, used by Alembic.
revision = '28caae1b112c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('address_info', sa.String(), nullable=True),
                    sa.Column('menu_info', sa.String(), nullable=True),
                    sa.Column(
                        'menu', sqlalchemy_json.NestedMutableJson(), nullable=True),
                    sa.Column(
                        'prices', sqlalchemy_json.NestedMutableJson(), nullable=True),
                    sa.Column(
                        'arabic', sqlalchemy_json.NestedMutableJson(), nullable=True),
                    sa.Column('password', sa.String(), nullable=True),
                    sa.Column('access_token', sa.String(), nullable=True),
                    sa.Column('is_setup', sa.Boolean(), nullable=True),
                    sa.Column('page_id', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('page_id'),
                    sa.UniqueConstraint(
                        'page_id', 'id', name='unique_vendor_customers'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('customers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('psid', sa.String(), nullable=True),
                    sa.Column('name', sa.String(length=80), nullable=True),
                    sa.Column('phone_number', sa.String(), nullable=True),
                    sa.Column('address', sa.String(), nullable=True),
                    sa.Column('created_time', sa.DateTime(), nullable=True),
                    sa.Column('page_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['page_id'], ['vendors.page_id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('psid'),
                    sa.UniqueConstraint(
                        'psid', 'id', name='unique_customer_orders')
                    )
    op.create_table('orders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('number', sa.Integer(), nullable=True),
                    sa.Column(
                        'items', sqlalchemy_json.NestedMutableJson(), nullable=True),
                    sa.Column('total', sa.Float(precision=3), nullable=True),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.Column('time', sa.DateTime(), nullable=True),
                    sa.Column('psid', sa.String(), nullable=True),
                    sa.Column('page_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['page_id'], ['vendors.page_id'], ),
                    sa.ForeignKeyConstraint(['psid'], ['customers.psid'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('number')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('customers')
    op.drop_table('vendors')
    # ### end Alembic commands ###
