"""empty message

Revision ID: 28caae1b112c
Revises: 
Create Date: 2020-02-23 00:13:15.687791

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_json


# revision identifiers, used by Alembic.
revision = '28caae1b112c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column(
        'open_hours', sa.DateTime(), nullable=True))
    op.add_column('vendors', sa.Column(
        'close_hours', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'open_hours')
    op.drop_column('vendors', 'close_hours')
    # ### end Alembic commands ###
