"""empty message

Revision ID: 33c3a0dbb80e
Revises: 8e56638aa93a
Create Date: 2020-02-22 23:56:30.430070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c3a0dbb80e'
down_revision = '8e56638aa93a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('address_info', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('menu_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'menu_info')
    op.drop_column('vendors', 'address_info')
    # ### end Alembic commands ###
