"""empty message

Revision ID: 28caae1b112c
Revises: 
Create Date: 2020-02-23 07:07:01.541769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28caae1b112c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'close_hours',
                    new_column_name='closing_hours', existing_type=sa.DateTime, type_=sa.Time)
    op.alter_column('vendors', 'opening_hours',
                    new_column_name='opening_hours', existing_type=sa.DateTime, type_=sa.Time)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'close_hours')
    op.drop_column('vendors', 'open_hours')
    # ### end Alembic commands ###
