"""empty message

Revision ID: ee99d4860cc5
Revises: None
Create Date: 2020-02-28 12:42:14.031645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee99d4860cc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'uid',
                    existing_type=sa.Integer, tyep_=sa.String)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('customers')
    op.drop_table('vendors')
    # ### end Alembic commands ###
